[platformio]
default_envs = due
build_dir = build/
src_dir = ./

[env:due]
platform = atmelsam
board = due
framework = arduino
build_unflags = -std=gnu++11 -std=c++1z -std=c++17
build_flags = -std=gnu++1z
extra_scripts = extra_script.py

upload_protocol = sam-ba
upload_command = bossac -i -b --port=$UPLOAD_PORT -U true -e -w $BUILD_DIR/${PROGNAME}.bin -R


;lib_deps = rjbatista/TM1638@^2.2.0